# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - microservices-contacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerpedlizar.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a870229afdff43b48f61e71a87b8a850 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e12ae706560b42879e1386bb89a3c6b7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerpedlizar.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a870229afdff43b48f61e71a87b8a850 }}/microservices-contacts-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'microservices-contacts'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c4278616a834ce185d01b0a08ec2b9f }}
        images: 'containerpedlizar.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a870229afdff43b48f61e71a87b8a850 }}/microservices-contacts-app:${{ github.sha }}'